# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: GAN-Deployment

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  apiGateway:
      binaryMediaTypes:
          - '*/*'
          - multipart/form-data
  environment:
    S3_BUCKET: tsai-assignment-models-s6
    MODEL_PATH: GAN_Indian_cars.onnx
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::tsai-assignment-models-s6/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: ./.serverless/.requirements_cache

# you can add packaging information here
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  generative_adversarial_network:
    handler: handler.generative_adversarial_network
    memoreSize: 3008
    timeout: 60
    events:
      - http:
          path: GAN
          method: get
          cors: true

plugins:
  - serverless-python-requirements
